services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      H2_DB_PATH: /app/data/bankingdb
    ports:
      - "8080:8080"
    volumes:
      - backend_h2_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: banking-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://backend:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend_h2_data:
